version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆
    groups:
      github-actions:
        patterns:
          - "*"
        cooldown:
          default-days: 7
  # Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆
    labels:
      - "internal"
    groups:
      python-packages:
        dependency-type: "development"
        patterns:
          - "*"
        cooldown:
          default-days: 7
