version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆
    cooldown:
      default-days: 7
    groups:
      github-actions:
        patterns:
          - "*"
  # Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆
    cooldown:
      default-days: 7
    groups:
      python-packages:
        dependency-type: "development"
        patterns:
          - "*"
